### PR TITLE
Fix commit cmd for metadata file

### PR DESCRIPTION
**Pull request by aq17**
We already format `metadatapath` above, so we can just run `git add metadatapath`

### CODE REVIEW

**Review by iwahbe — CHANGES_REQUESTED** [review]
I don't understand why this change is necessary or ok. 

Also, if we are not running the tool in the repo we are using, `git` could add this file to the wrong repo. The `step.Cmd.In` method sets the CWD for the `git` command being run.

**Comment by aq17** [comment]
You're right. I think I misunderstood what's causing this issue:
```
 /usr/bin/git add home/runner/work/pulumi-digitalocean/provider/cmd/pulumi-resour...: exit status 128:
fatal: pathspec 'home/runner/work/pulumi-digitalocean/provider/cmd/pulumi-resource-digitalocean/bridge-metadata.json' did not match any files
```
(https://github.com/pulumi/pulumi-digitalocean/actions/runs/4800654784/jobs/8541866350)


This change "worked", but the file paths look equivalent
```
 /usr/bin/git add home/runner/work/pulumi-digitalocean/provider/cmd/pulumi-resour...: done
  - Add AutoAliasing
 Add AutoAliasing: done
```
https://github.com/pulumi/pulumi-digitalocean/actions/runs/4800819140/jobs/8542231333

**Comment by aq17** [comment]
I'm still getting the same error when running `git add {full_metadata_file_path}` https://github.com/pulumi/pulumi-digitalocean/actions/runs/4801775200/jobs/8544418386

https://github.com/pulumi/upgrade-provider/pull/56/commits/4866fb832d80afd205312b67612bf8dbf7dd512c seems to work
https://github.com/pulumi/pulumi-digitalocean/actions/runs/4801860932/jobs/8544607514 

Again, I don't quite see how they're any functionally different

**Comment by iwahbe** [comment]
Can you try with https://github.com/pulumi/upgrade-provider/commit/9e79d2320fc2f3f148476ffe3460a8afa797d9c7? Previously `{full_metadata_file_path}` was wrong.

**Comment by aq17** [comment]
Thanks looks okay now https://github.com/pulumi/pulumi-digitalocean/actions/runs/4802009116/jobs/8544939730.

**Pull request closed without merging**
